import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  inject,
  OnInit,
  OnDestroy,
  signal,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CdkDragDrop, DragDropModule, moveItemInArray } from '@angular/cdk/drag-drop';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatDialogModule } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { Router } from '@angular/router';
import { SidebarComponent } from '../../components/sidebar/sidebar';
import { HeaderComponent } from '../../components/header/header';
import { ProgressTrackerComponent } from '../../components/progress-tracker/progress-tracker';
import { DrillCardComponent } from '../../components/drill-card/drill-card';
import { DrillLibrarySidebarComponent } from '../../components/drill-library-sidebar/drill-library-sidebar';
import { Button } from '../../components/button/button';
import { Drill } from '../../models/drill.model';
import { TrainingEvent } from '../../models/training-event.model';
import { BuilderStateService } from '../../services/builder-state.service';
import { SidebarStateService } from '../../services/sidebar-state.service';
import { TrainingService } from '../../services/training.service';

@Component({
  selector: 'training-builder',
  standalone: true,
  templateUrl: './training-builder.html',
  styleUrl: './training-builder.css',
  imports: [
    CommonModule,
    FormsModule,
    DragDropModule,
    MatSidenavModule,
    MatSnackBarModule,
    MatDialogModule,
    MatIconModule,
    SidebarComponent,
    HeaderComponent,
    ProgressTrackerComponent,
    DrillCardComponent,
    DrillLibrarySidebarComponent,
    Button,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})


export class TrainingBuilderComponent implements OnInit, OnDestroy {
  readonly sidebarState = inject(SidebarStateService);
  get isSidebarExpanded(): boolean { return this.sidebarState.isExpanded; }
  totalDuration = 0;
  sessionTitle = '';
  titleIsAutoGenerated = false;
  showDatePicker = false;
  manualDate: string = '';
  manualTime: string = '09:00';
  isSaving = false;

  drills: Drill[] = [];

  private readonly builderState = inject(BuilderStateService);
  private readonly trainingService = inject(TrainingService);
  private readonly snackBar = inject(MatSnackBar);
  private readonly router = inject(Router);
  private readonly cdr = inject(ChangeDetectorRef);

  get goal(): number {
    return this.builderState.goalDuration();
  }

  get isMaxDuration(): boolean {
    return this.totalDuration >= this.goal;
  }

  remainingFor(drill: Drill): number {
    const others = this.drills
      .filter((d) => d.id !== drill.id)
      .reduce((s, d) => s + (d.duration || 0), 0);
    return Math.max(0, this.goal - others);
  }

  get targetDate(): Date | null {
    return this.builderState.targetDate();
  }

  get startTime(): string {
    return this.builderState.startTime();
  }

  get isReuseMode(): boolean {
    const ev = this.builderState.existingEvent();
    return ev !== null && ev.id === -1;
  }

  ngOnInit(): void {
    const existing = this.builderState.existingEvent();
    if (existing) {
      this.sessionTitle = existing.title;
      this.drills = (existing.drills ?? []).map((d, i) => ({
        id: String(i + 1),
        title: d.name,
        duration: Math.floor((existing.duration ?? 60) / (existing.drills?.length ?? 1)),
        level: 'Beginner' as const,
      }));
      // Reuse mode: always show date/time picker so coach can set start time
      if (this.isReuseMode) {
        this.showDatePicker = true;
        // Pre-fill date if already selected (e.g. from "Use Existing Practice" calendar click)
        const preDate = this.builderState.targetDate();
        if (preDate) {
          const y = preDate.getFullYear();
          const m = String(preDate.getMonth() + 1).padStart(2, '0');
          const d = String(preDate.getDate()).padStart(2, '0');
          this.manualDate = `${y}-${m}-${d}`;
        }
      }
    } else {
      this.drills = [];
    }

    // Auto-generate title if still empty
    if (!this.sessionTitle) {
      this.sessionTitle = this.buildAutoTitle(this.builderState.targetDate());
      this.titleIsAutoGenerated = true;
    }

    this.calculateTotalDuration();
  }

  ngOnDestroy() {
    this.builderState.clear();
  }
  onExpandedChange(expanded: boolean): void {
    this.sidebarState.isExpanded = expanded;
  }

  drop(event: CdkDragDrop<Drill[]>): void {
    if (event.previousContainer === event.container) {
      moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
    }
  }

  onDrillAdd(drill: Drill): void {
    if (this.isMaxDuration) return;
    this.drills = [...this.drills, { ...drill, id: Date.now().toString() }];
    this.calculateTotalDuration();
    this.cdr.markForCheck();
  }

  onDeleteDrill(drillId: string): void {
    this.drills = this.drills.filter((d) => d.id !== drillId);
    this.calculateTotalDuration();
    this.cdr.markForCheck();
  }

  onDurationChanged(event: { drillId: string; duration: number }): void {
    const drill = this.drills.find((d) => d.id === event.drillId);
    if (drill) {
      drill.duration = Math.min(event.duration, this.remainingFor(drill));
      this.calculateTotalDuration();
      this.cdr.markForCheck();
    }
  }

  saveToCalendar(): void {
    if (this.totalDuration < this.goal) {
      const remaining = this.goal - this.totalDuration;
      this.snackBar.open(
        `Session is ${this.totalDuration} min — still ${remaining} min short of the ${this.goal} min goal.`,
        'Close',
        { duration: 4000, panelClass: 'snack-error' },
      );
      return;
    }

    const date = this.builderState.targetDate();
    if (!date) {
      this.showDatePicker = true;
      this.cdr.markForCheck();
      return;
    }
    this.persistSession(date);
  }

  onManualDateConfirm(): void {
    if (!this.manualDate) return;
    const date = new Date(this.manualDate + 'T00:00:00');
    this.builderState.setDate(date);
    this.builderState.setStartTime(this.manualTime);
    this.showDatePicker = false;
    if (this.titleIsAutoGenerated) {
      this.sessionTitle = this.buildAutoTitle(date);
    }
    this.persistSession(date);
  }

  onManualDateCancel(): void {
    this.showDatePicker = false;
    this.cdr.markForCheck();
  }

  toggleDatePicker(): void {
    this.showDatePicker = !this.showDatePicker;
    this.cdr.markForCheck();
  }

  onTitleInput(): void {
    this.titleIsAutoGenerated = false;
  }

  private buildAutoTitle(date: Date | null): string {
    const focus = this.builderState.plannedFocus()
      ?? this.builderState.existingEvent()?.focus
      ?? 'Practice';
    const dateStr = date
      ? `${date.toLocaleString('en-US', { month: 'short' })} ${date.getDate()}`
      : '';
    return dateStr ? `${focus} · ${dateStr}` : focus;
  }

  private persistSession(date: Date): void {
    if (this.isSaving) return;
    this.isSaving = true;
    this.cdr.markForCheck();

    const title = this.sessionTitle.trim() || 'Custom Training';
    const existing = this.builderState.existingEvent();
    const isNew = !existing || existing.id === -1;

    const newEvent: TrainingEvent = {
      id: isNew ? this.trainingService.getNextId() : existing!.id,
      date,
      title,
      color: 'red',
      duration: this.totalDuration,
      startTime: this.builderState.startTime(),
      intensity: 'MEDIUM',
      focus: 'Custom session',
      ageGroup: 'U18',
      drills: this.drills.map((d, i) => ({ id: i + 1, name: d.title, duration: d.duration ?? 0 })),
    };

    // ── Save to backend ──────────────────────────────────────────────────────
    const backendCall = isNew
      ? this.trainingService.saveSession(newEvent)
      : this.trainingService.editSession(existing!.id, newEvent);

    backendCall.subscribe({
      next: () => {
        this.isSaving = false;
        if (!isNew) {
          this.trainingService.updateEvent(newEvent);
        } else {
          this.trainingService.addEvent(newEvent);
        }
        this.builderState.clear();
        this.snackBar.open(`"${title}" saved to calendar!`, 'Close', { duration: 3000, panelClass: 'snack-success' });
        this.router.navigate(['/planner']);
      },
      error: (err) => {
        this.isSaving = false;
        const msg = err.status === 409
          ? (err.error?.error ?? 'This session overlaps with an existing one.')
          : 'Failed to save. Please try again.';
        this.snackBar.open(msg, 'Close', {
          duration: 5000,
          panelClass: 'snack-error',
        });
        this.cdr.markForCheck();
      },
    });
  }

  private calculateTotalDuration(): void {
    this.totalDuration = this.drills.reduce((sum, d) => sum + (d.duration || 0), 0);
  }
}
