import { Injectable, signal } from '@angular/core';

export type AppLanguage = 'en' | 'bs';
type Dictionary = Record<string, string>;

const EN: Dictionary = {
  'nav.dashboard':'Dashboard','nav.roster':'Roster','nav.importStatistics':'Import Statistics','nav.drills':'Drills','nav.playbook':'Playbook','nav.planner':'Planner','nav.coaches':'Coaches',
  'common.save':'Save','common.cancel':'Cancel','common.close':'Close','common.back':'Back','common.next':'Next','common.delete':'Delete','common.edit':'Edit','common.loading':'Loading…','common.retry':'Retry','common.search':'Search','common.create':'Create','common.confirm':'Confirm',
  'header.openMenu':'Open menu','header.editProfile':'Edit profile','header.logout':'Logout',
  'dashboard.teamPerformance':'Team Performance','dashboard.coachDecision':'Coach decision dashboard','dashboard.importGame':'Import Game','dashboard.loading':'Loading team performance…','dashboard.noGameData':'No game data yet','dashboard.noGameDataHint':'Import your first game to start seeing team performance and coaching insights.','dashboard.recentPerformance':'Recent Performance','dashboard.strengths':'Team Strengths','dashboard.improve':'Areas to Improve','dashboard.coachingInsights':'Coaching Insights','dashboard.focusNext':'What to focus on next','dashboard.recentGames':'Recent Games','dashboard.gameLog':'Game Log','dashboard.noRecommendations':'No coaching recommendations yet. Import more game data to generate personalized coaching insights.',
  'drills.title':'Drill Library','drills.subtitle':'Manage your drill collection and import new drills from PDF','drills.add':'Add Drill','drills.choose':'Choose how you want to add a drill to your library.','drills.createManual':'Create Manually','drills.createManualHint':'Enter drill details using the standard form.','drills.importAI':'Import with AI','drills.importAIHint':'Upload a PDF or image for extraction and review.','drills.create':'Create Drill','drills.name':'Drill Name','drills.description':'Description','drills.focus':'Focus','drills.intensity':'Intensity','drills.equipment':'Equipment','drills.complexity':'Complexity','drills.search':'Search drills…',
  'insights.recommendation':'Coaching Recommendation','insights.priority':'Coaching Priority','insights.currentPerformance':'Current performance','insights.why':'Why this matters','insights.trainingFocus':'Recommended training focus','insights.drills':'Recommended drills','insights.noDrills':'Drill recommendations are not available yet.','insights.view':'View recommendation','insights.useful':'Was this recommendation useful?','insights.yes':'Yes','insights.no':'No','insights.continuePlanner':'Continue to training planner','insights.feedbackTitle':'Help us improve this recommendation','insights.feedbackQuestion':"What wasn't useful?",'insights.notRelevant':'Not relevant to my team','insights.alreadyWorking':'We’re already working on this','insights.disagree':'I don’t agree with the analysis','insights.drillsDontFit':'Recommended drills don’t fit my team','insights.other':'Other','insights.comment':'Additional comment (optional)','insights.submit':'Submit feedback','insights.thanks':'Thanks for the feedback.'
};
const BS: Dictionary = {
  'nav.dashboard':'Kontrolna tabla','nav.roster':'Sastav ekipe','nav.importStatistics':'Uvezi statistiku','nav.drills':'Vježbe','nav.playbook':'Knjiga akcija','nav.planner':'Planer treninga','nav.coaches':'Treneri',
  'common.save':'Sačuvaj','common.cancel':'Otkaži','common.close':'Zatvori','common.back':'Nazad','common.next':'Dalje','common.delete':'Obriši','common.edit':'Uredi','common.loading':'Učitavanje…','common.retry':'Pokušaj ponovo','common.search':'Pretraži','common.create':'Kreiraj','common.confirm':'Potvrdi',
  'header.openMenu':'Otvori meni','header.editProfile':'Uredi profil','header.logout':'Odjava',
  'dashboard.teamPerformance':'Učinak ekipe','dashboard.coachDecision':'Kontrolna tabla za trenerske odluke','dashboard.importGame':'Uvezi utakmicu','dashboard.loading':'Učitavanje učinka ekipe…','dashboard.noGameData':'Još nema podataka o utakmicama','dashboard.noGameDataHint':'Uvezite prvu utakmicu da biste vidjeli učinak ekipe i trenerske uvide.','dashboard.recentPerformance':'Nedavni učinak','dashboard.strengths':'Prednosti ekipe','dashboard.improve':'Područja za poboljšanje','dashboard.coachingInsights':'Trenerski uvidi','dashboard.focusNext':'Na šta se fokusirati dalje','dashboard.recentGames':'Nedavne utakmice','dashboard.gameLog':'Pregled utakmica','dashboard.noRecommendations':'Još nema trenerskih preporuka. Uvezite više utakmica za personalizirane uvide.',
  'drills.title':'Biblioteka vježbi','drills.subtitle':'Upravljajte kolekcijom vježbi i uvezite nove iz PDF-a','drills.add':'Dodaj vježbu','drills.choose':'Odaberite način dodavanja vježbe u biblioteku.','drills.createManual':'Kreiraj ručno','drills.createManualHint':'Unesite detalje vježbe kroz standardni obrazac.','drills.importAI':'Uvezi uz AI','drills.importAIHint':'Prenesite PDF ili sliku za izdvajanje i pregled.','drills.create':'Kreiraj vježbu','drills.name':'Naziv vježbe','drills.description':'Opis','drills.focus':'Fokus','drills.intensity':'Intenzitet','drills.equipment':'Oprema','drills.complexity':'Složenost','drills.search':'Pretraži vježbe…',
  'insights.recommendation':'Trenerska preporuka','insights.priority':'Trenerski prioritet','insights.currentPerformance':'Trenutni učinak','insights.why':'Zašto je ovo važno','insights.trainingFocus':'Preporučeni fokus treninga','insights.drills':'Preporučene vježbe','insights.noDrills':'Preporuke za vježbe još nisu dostupne.','insights.view':'Pogledaj preporuku','insights.useful':'Je li ova preporuka bila korisna?','insights.yes':'Da','insights.no':'Ne','insights.continuePlanner':'Nastavi u planer treninga','insights.feedbackTitle':'Pomozite nam da poboljšamo preporuku','insights.feedbackQuestion':'Šta nije bilo korisno?','insights.notRelevant':'Nije relevantno za moju ekipu','insights.alreadyWorking':'Već radimo na tome','insights.disagree':'Ne slažem se s analizom','insights.drillsDontFit':'Preporučene vježbe ne odgovaraju mojoj ekipi','insights.other':'Ostalo','insights.comment':'Dodatni komentar (nije obavezan)','insights.submit':'Pošalji povratnu informaciju','insights.thanks':'Hvala na povratnoj informaciji.'
};

@Injectable({ providedIn: 'root' })
export class TranslationService {
  readonly language = signal<AppLanguage>(typeof localStorage !== 'undefined' && localStorage.getItem('coaching-app-language') === 'bs' ? 'bs' : 'en');
  setLanguage(language: AppLanguage) { this.language.set(language); if (typeof localStorage !== 'undefined') localStorage.setItem('coaching-app-language', language); }
  translate(key: string) { return (this.language() === 'bs' ? BS : EN)[key] ?? EN[key] ?? key; }
}
